---
    - hosts: all
      become: yes
      tasks:
      - name: install java on nodes
        apt:
         name: default-jdk
         state: present
      - name: install docker on nodes
        apt:
         name: docker.io
         state: present 
