---
- hosts: all
  become: yes
  tasks:
  - name: install docker
    apt:
     name: docker.io
     state: present
    tags:
    - dockerpackage

  - name: install java
    apt:
     name: default-jdk
     state: present
    tags:
    - javapackage

  - name: install maven
    apt:
     name: maven
     state: present
    tags:
    - mavenpackage

#### command
>> ansible-playbook -i hosts tags.yaml --tags=javapackage
