---
- hosts: appserver
  become: yes
  tasks:
  - name: i want to install nginx on appserver
    apt:
      name: nginx
      state: present

  - name: start the service
    service:
      name: nginx
      state: started

  - name: i want to copy index file into all nodes
    template:
      src: index.j2
      dest: /usr/share/nginx/html/index.html
